import { execFileSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";

import {
  createIanaTzdbResolver,
  createEntry,
  getSampleDates,
  shouldIncludeTimeZone,
  serializeEntries,
  serializeEntry,
  IANA_TZDB_SOURCE_FILES,
  type TimeZoneAbbreviations,
} from "./utils.ts";

const year = new Date().getUTCFullYear();
const sampleDates = getSampleDates(year);
const ianaTzdb = createIanaTzdbResolver();
const canonicalTimeZones = await getCanonicalTimeZones();
const runtimeSupportedTimeZones = getRuntimeSupportedTimeZones();

const timeZones = [...canonicalTimeZones]
  .filter((timeZone) => isAcceptedTimeZone(timeZone))
  .toSorted((timeZoneA, timeZoneB) => timeZoneA.localeCompare(timeZoneB));
const aliasGroups = await createAliasGroups(canonicalTimeZones, runtimeSupportedTimeZones);

if (!timeZones.includes("UTC")) {
  timeZones.unshift("UTC");
}

try {
  const entries = Object.fromEntries(
    timeZones.map((timeZone) => [timeZone, createEntry(timeZone, sampleDates, ianaTzdb.resolveVariant)]),
  );

  await writeAliasFile("../src/timezone-aliases.ts", aliasGroups, ianaTzdb.version);
  await writeAbbreviationFile("../src/timezone-abbreviations.ts", entries, ianaTzdb.version);
} finally {
  ianaTzdb.dispose();
}

async function writeAbbreviationFile(
  path: string,
  abbreviations: TimeZoneAbbreviations,
  tzdbVersion: string,
): Promise<void> {
  const output = `// Generated by scripts/generate-abbreviations.ts.
// Source: IANA tzdb ${tzdbVersion}, sampled at year ${year}.
// This is a current-ish lookup. Regenerate after updating pinned IANA tzdb.

export type TimeZoneAbbreviationEntry = Record<string, string>;

export const TIME_ZONE_ABBREVIATIONS = {
${serializeEntries(abbreviations, serializeEntry)}
} as const satisfies Record<
  string,
  TimeZoneAbbreviationEntry
>;
`;

  await writeFile(new URL(path, import.meta.url), output);
}

async function writeAliasFile(
  path: string,
  aliasGroups: readonly (readonly string[])[],
  tzdbVersion: string,
): Promise<void> {
  const output = `// Generated by scripts/generate-abbreviations.ts.
// Source: IANA tzdb ${tzdbVersion}.
// Groups are [canonical, ...aliases], where canonical names come from tzdb
// canonical sources and aliases are non-canonical names present in
// Intl.supportedValuesOf("timeZone") from either Node or Bun runtimes.
export const TIME_ZONE_ALIAS_GROUPS = [
${aliasGroups.map((aliases) => `  [${aliases.map((alias) => JSON.stringify(alias)).join(", ")}],`).join("\n")}
] as const;
`;

  await writeFile(new URL(path, import.meta.url), output);
}

async function createAliasGroups(
  canonicalSet: ReadonlySet<string>,
  runtimeSupportedTimeZones: ReadonlySet<string>,
): Promise<readonly (readonly string[])[]> {
  const components = await getLinkedTimeZoneComponents();
  const groups: string[][] = [];

  for (const names of components.values()) {
    const canonicalNames = [...names]
      .filter((name) => canonicalSet.has(name) && isAcceptedTimeZone(name))
      .toSorted((nameA, nameB) => nameA.localeCompare(nameB));
    const canonicalName = canonicalNames[0];

    if (!canonicalName) {
      continue;
    }

    const canonicalArea = getArea(canonicalName);
    const supportedAliasNames = [...names]
      .filter((name) => {
        return (
          !canonicalSet.has(name) &&
          runtimeSupportedTimeZones.has(name) &&
          isIanaStyleName(name) &&
          getArea(name) === canonicalArea
        );
      })
      .toSorted((nameA, nameB) => nameA.localeCompare(nameB));

    if (supportedAliasNames.length === 0) {
      continue;
    }

    groups.push([canonicalName, ...supportedAliasNames]);
  }

  const sortedGroups = groups.toSorted((groupA, groupB) => groupA[0].localeCompare(groupB[0]));
  validateAliasGroups(sortedGroups, canonicalSet, runtimeSupportedTimeZones);

  return sortedGroups;
}

function validateAliasGroups(
  aliasGroups: readonly (readonly string[])[],
  canonicalSet: ReadonlySet<string>,
  runtimeSupportedTimeZones: ReadonlySet<string>,
): void {
  for (const aliasGroup of aliasGroups) {
    const [canonicalName, ...aliases] = aliasGroup;

    if (!canonicalName || aliases.length === 0) {
      throw new Error(`Invalid alias group shape: ${JSON.stringify(aliasGroup)}`);
    }

    if (!canonicalSet.has(canonicalName)) {
      throw new Error(`Alias group canonical name is not canonical: ${canonicalName}`);
    }

    for (const alias of aliases) {
      if (canonicalSet.has(alias)) {
        throw new Error(`Alias entry is canonical but should be a non-canonical alias: ${alias}`);
      }

      if (!runtimeSupportedTimeZones.has(alias)) {
        throw new Error(
          `Alias entry is not present in Intl.supportedValuesOf(\"timeZone\") for Node/Bun: ${alias}`,
        );
      }
    }
  }
}

async function getLinkedTimeZoneComponents(): Promise<Map<string, Set<string>>> {
  const allNames = new Set<string>();
  const edges: [string, string][] = [];

  for (const sourceFile of IANA_TZDB_SOURCE_FILES) {
    const source = await readPinnedTzdbFile(sourceFile);

    for (const line of source.split(/\r?\n/)) {
      const trimmed = line.trim();

      if (!trimmed || trimmed.startsWith("#")) {
        continue;
      }

      const [keyword, target, linkName] = trimmed.split(/\s+/);

      if (keyword !== "Link" || !target || !linkName) {
        continue;
      }

      if (!shouldIncludeTimeZone(target) || !shouldIncludeTimeZone(linkName)) {
        continue;
      }

      allNames.add(target);
      allNames.add(linkName);
      edges.push([target, linkName]);
    }
  }

  const parents = new Map<string, string>();

  for (const name of allNames) {
    parents.set(name, name);
  }

  const find = (name: string): string => {
    const parent = parents.get(name);

    if (!parent) {
      parents.set(name, name);
      return name;
    }

    if (parent === name) {
      return name;
    }

    const root = find(parent);
    parents.set(name, root);
    return root;
  };

  const union = (nameA: string, nameB: string): void => {
    const rootA = find(nameA);
    const rootB = find(nameB);

    if (rootA !== rootB) {
      parents.set(rootB, rootA);
    }
  };

  for (const [target, linkName] of edges) {
    union(target, linkName);
  }

  const components = new Map<string, Set<string>>();

  for (const name of allNames) {
    const root = find(name);
    const component = components.get(root);

    if (component) {
      component.add(name);
    } else {
      components.set(root, new Set([name]));
    }
  }

  return components;
}

async function getCanonicalTimeZones(): Promise<Set<string>> {
  const names = new Set<string>();
  const files = ["zone.tab", "zone1970.tab"];

  for (const fileName of files) {
    const source = await readPinnedTzdbFile(fileName);

    for (const line of source.split(/\r?\n/)) {
      if (!line || line.startsWith("#")) {
        continue;
      }

      const columns = line.split("\t");
      const name = columns[2];

      if (name && shouldIncludeTimeZone(name)) {
        names.add(name);
      }
    }
  }

  return names;
}

async function readPinnedTzdbFile(fileName: string): Promise<string> {
  try {
    return await readFile(new URL(`./tzdb/data/${fileName}`, import.meta.url), "utf8");
  } catch (error) {
    throw new Error(
      `Pinned IANA tzdb file "${fileName}" is missing. Run \`npm run generate\` (or \`npm run update-tzdb\`) and retry.`,
      { cause: error },
    );
  }
}

function isAcceptedTimeZone(timeZone: string): boolean {
  try {
    new Intl.DateTimeFormat("en-US", { timeZone });
    return true;
  } catch {
    return false;
  }
}

function isIanaStyleName(timeZone: string): boolean {
  return timeZone.includes("/");
}

function getArea(timeZone: string): string {
  return timeZone.split("/", 1)[0] ?? "";
}

function getRuntimeSupportedTimeZones(): Set<string> {
  const supported = new Set<string>();
  const isNodeRuntime = typeof process.versions.node === "string" && !("bun" in process.versions);
  const isBunRuntime = "bun" in process.versions;

  for (const timeZone of Intl.supportedValuesOf("timeZone")) {
    if (shouldIncludeTimeZone(timeZone)) {
      supported.add(timeZone);
    }
  }

  const runners = [
    !isNodeRuntime
      ? {
          command: "node",
          args: [
            "--input-type=module",
            "-e",
            "process.stdout.write(JSON.stringify(Intl.supportedValuesOf('timeZone')))",
          ],
          label: "node",
        }
      : undefined,
    !isBunRuntime
      ? {
          command: "bun",
          args: ["--eval", "process.stdout.write(JSON.stringify(Intl.supportedValuesOf('timeZone')))"],
          label: "bun",
        }
      : undefined,
  ].filter((runner) => runner !== undefined);

  for (const runner of runners) {
    try {
      const output = execFileSync(runner.command, runner.args, {
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      });
      const parsed = JSON.parse(output) as unknown;

      if (!Array.isArray(parsed)) {
        throw new Error(`Expected an array, received ${typeof parsed}.`);
      }

      for (const timeZone of parsed) {
        if (typeof timeZone === "string" && shouldIncludeTimeZone(timeZone)) {
          supported.add(timeZone);
        }
      }
    } catch (error) {
      console.warn(`Unable to query ${runner.label} supported time zones: ${String(error)}`);
    }
  }

  return supported;
}
