import { execFileSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";

import {
  createIanaTzdbResolver,
  createEntry,
  getSampleDates,
  shouldIncludeTimeZone,
  serializeEntries,
  serializeEntry,
  IANA_TZDB_SOURCE_FILES,
  type TimeZoneOffsetEntry,
  type TimeZoneAbbreviations,
} from "./utils.ts";

const year = new Date().getUTCFullYear();
const sampleDates = getSampleDates(year);
const ianaTzdb = createIanaTzdbResolver();
const canonicalTimeZones = await getCanonicalTimeZones();
const runtimeSupportedTimeZones = getRuntimeSupportedTimeZones();

const timeZones = [...canonicalTimeZones]
  .filter((timeZone) => isAcceptedTimeZone(timeZone))
  .toSorted((timeZoneA, timeZoneB) => timeZoneA.localeCompare(timeZoneB));
const aliasGroups = await createAliasGroups(canonicalTimeZones, runtimeSupportedTimeZones);
const offsetFormatterCache = new Map<string, Intl.DateTimeFormat>();
const monthDayFormatterCache = new Map<string, Intl.DateTimeFormat>();
const MS_PER_DAY = 24 * 60 * 60 * 1000;
const MS_PER_HOUR = 60 * 60 * 1000;
const MS_PER_MINUTE = 60 * 1000;

if (!timeZones.includes("UTC")) {
  timeZones.unshift("UTC");
}

try {
  const { entries, transitionLookup } = createEntriesWithTransitionLookup(
    timeZones,
    sampleDates,
    ianaTzdb.resolveVariant,
  );

  await writeAliasFile("../src/timezone-aliases.ts", aliasGroups, ianaTzdb.version);
  await writeTransitionLookupFile("../src/timezone-transitions.ts", transitionLookup, ianaTzdb.version);
  await writeAbbreviationFile("../src/timezone-abbreviations.ts", entries, ianaTzdb.version);
} finally {
  ianaTzdb.dispose();
}

async function writeAbbreviationFile(
  path: string,
  abbreviations: TimeZoneAbbreviations,
  tzdbVersion: string,
): Promise<void> {
  const output = `// Generated by scripts/generate-abbreviations.ts.
// Source: IANA tzdb ${tzdbVersion}, sampled at year ${year}.
// This is a current-ish lookup. Regenerate after updating pinned IANA tzdb.

export type TimeZoneAbbreviationEntry = Record<string, string>;

export const TIME_ZONE_ABBREVIATIONS = {
${serializeEntries(abbreviations, serializeEntry)}
} as const satisfies Record<
  string,
  TimeZoneAbbreviationEntry
>;
`;

  await writeFile(new URL(path, import.meta.url), output);
}

async function writeTransitionLookupFile(
  path: string,
  lookup: readonly string[],
  tzdbVersion: string,
): Promise<void> {
  const output = `// Generated by scripts/generate-abbreviations.ts.
// Source: IANA tzdb ${tzdbVersion}, transition signatures sampled at year ${year}.
export const TIME_ZONE_TRANSITION_LOOKUP = [
${lookup.map((signature) => `  ${JSON.stringify(signature)},`).join("\n")}
] as const;
`;

  await writeFile(new URL(path, import.meta.url), output);
}

async function writeAliasFile(
  path: string,
  aliasGroups: readonly (readonly string[])[],
  tzdbVersion: string,
): Promise<void> {
  const output = `// Generated by scripts/generate-abbreviations.ts.
// Source: IANA tzdb ${tzdbVersion}.
// Groups are [canonical, ...aliases], where canonical names come from tzdb
// canonical sources and aliases are non-canonical names present in
// Intl.supportedValuesOf("timeZone") from either Node or Bun runtimes.
export const TIME_ZONE_ALIAS_GROUPS = [
${aliasGroups.map((aliases) => `  [${aliases.map((alias) => JSON.stringify(alias)).join(", ")}],`).join("\n")}
] as const;
`;

  await writeFile(new URL(path, import.meta.url), output);
}

async function createAliasGroups(
  canonicalSet: ReadonlySet<string>,
  runtimeSupportedTimeZones: ReadonlySet<string>,
): Promise<readonly (readonly string[])[]> {
  const components = await getLinkedTimeZoneComponents();
  const groups: string[][] = [];

  for (const names of components.values()) {
    const canonicalNames = [...names]
      .filter((name) => canonicalSet.has(name) && isAcceptedTimeZone(name))
      .toSorted((nameA, nameB) => nameA.localeCompare(nameB));
    const canonicalName = canonicalNames[0];

    if (!canonicalName) {
      continue;
    }

    const canonicalArea = getArea(canonicalName);
    const supportedAliasNames = [...names]
      .filter((name) => {
        return (
          !canonicalSet.has(name) &&
          runtimeSupportedTimeZones.has(name) &&
          isIanaStyleName(name) &&
          getArea(name) === canonicalArea
        );
      })
      .toSorted((nameA, nameB) => nameA.localeCompare(nameB));

    if (supportedAliasNames.length === 0) {
      continue;
    }

    groups.push([canonicalName, ...supportedAliasNames]);
  }

  const sortedGroups = groups.toSorted((groupA, groupB) => groupA[0].localeCompare(groupB[0]));
  validateAliasGroups(sortedGroups, canonicalSet, runtimeSupportedTimeZones);

  return sortedGroups;
}

function validateAliasGroups(
  aliasGroups: readonly (readonly string[])[],
  canonicalSet: ReadonlySet<string>,
  runtimeSupportedTimeZones: ReadonlySet<string>,
): void {
  for (const aliasGroup of aliasGroups) {
    const [canonicalName, ...aliases] = aliasGroup;

    if (!canonicalName || aliases.length === 0) {
      throw new Error(`Invalid alias group shape: ${JSON.stringify(aliasGroup)}`);
    }

    if (!canonicalSet.has(canonicalName)) {
      throw new Error(`Alias group canonical name is not canonical: ${canonicalName}`);
    }

    for (const alias of aliases) {
      if (canonicalSet.has(alias)) {
        throw new Error(`Alias entry is canonical but should be a non-canonical alias: ${alias}`);
      }

      if (!runtimeSupportedTimeZones.has(alias)) {
        throw new Error(
          `Alias entry is not present in Intl.supportedValuesOf(\"timeZone\") for Node/Bun: ${alias}`,
        );
      }
    }
  }
}

async function getLinkedTimeZoneComponents(): Promise<Map<string, Set<string>>> {
  const allNames = new Set<string>();
  const edges: [string, string][] = [];

  for (const sourceFile of IANA_TZDB_SOURCE_FILES) {
    const source = await readPinnedTzdbFile(sourceFile);

    for (const line of source.split(/\r?\n/)) {
      const trimmed = line.trim();

      if (!trimmed || trimmed.startsWith("#")) {
        continue;
      }

      const [keyword, target, linkName] = trimmed.split(/\s+/);

      if (keyword !== "Link" || !target || !linkName) {
        continue;
      }

      if (!shouldIncludeTimeZone(target) || !shouldIncludeTimeZone(linkName)) {
        continue;
      }

      allNames.add(target);
      allNames.add(linkName);
      edges.push([target, linkName]);
    }
  }

  const parents = new Map<string, string>();

  for (const name of allNames) {
    parents.set(name, name);
  }

  const find = (name: string): string => {
    const parent = parents.get(name);

    if (!parent) {
      parents.set(name, name);
      return name;
    }

    if (parent === name) {
      return name;
    }

    const root = find(parent);
    parents.set(name, root);
    return root;
  };

  const union = (nameA: string, nameB: string): void => {
    const rootA = find(nameA);
    const rootB = find(nameB);

    if (rootA !== rootB) {
      parents.set(rootB, rootA);
    }
  };

  for (const [target, linkName] of edges) {
    union(target, linkName);
  }

  const components = new Map<string, Set<string>>();

  for (const name of allNames) {
    const root = find(name);
    const component = components.get(root);

    if (component) {
      component.add(name);
    } else {
      components.set(root, new Set([name]));
    }
  }

  return components;
}

async function getCanonicalTimeZones(): Promise<Set<string>> {
  const names = new Set<string>();
  const files = ["zone.tab", "zone1970.tab"];

  for (const fileName of files) {
    const source = await readPinnedTzdbFile(fileName);

    for (const line of source.split(/\r?\n/)) {
      if (!line || line.startsWith("#")) {
        continue;
      }

      const columns = line.split("\t");
      const name = columns[2];

      if (name && shouldIncludeTimeZone(name)) {
        names.add(name);
      }
    }
  }

  return names;
}

async function readPinnedTzdbFile(fileName: string): Promise<string> {
  try {
    return await readFile(new URL(`./tzdb/data/${fileName}`, import.meta.url), "utf8");
  } catch (error) {
    throw new Error(
      `Pinned IANA tzdb file "${fileName}" is missing. Run \`npm run generate\` (or \`npm run update-tzdb\`) and retry.`,
      { cause: error },
    );
  }
}

function isAcceptedTimeZone(timeZone: string): boolean {
  try {
    new Intl.DateTimeFormat("en-US", { timeZone });
    return true;
  } catch {
    return false;
  }
}

function isIanaStyleName(timeZone: string): boolean {
  return timeZone.includes("/");
}

function getArea(timeZone: string): string {
  return timeZone.split("/", 1)[0] ?? "";
}

function getRuntimeSupportedTimeZones(): Set<string> {
  const supported = new Set<string>();
  const isNodeRuntime = typeof process.versions.node === "string" && !("bun" in process.versions);
  const isBunRuntime = "bun" in process.versions;

  for (const timeZone of Intl.supportedValuesOf("timeZone")) {
    if (shouldIncludeTimeZone(timeZone)) {
      supported.add(timeZone);
    }
  }

  const runners = [
    !isNodeRuntime
      ? {
          command: "node",
          args: [
            "--input-type=module",
            "-e",
            "process.stdout.write(JSON.stringify(Intl.supportedValuesOf('timeZone')))",
          ],
          label: "node",
        }
      : undefined,
    !isBunRuntime
      ? {
          command: "bun",
          args: ["--eval", "process.stdout.write(JSON.stringify(Intl.supportedValuesOf('timeZone')))"],
          label: "bun",
        }
      : undefined,
  ].filter((runner) => runner !== undefined);

  for (const runner of runners) {
    try {
      const output = execFileSync(runner.command, runner.args, {
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      });
      const parsed = JSON.parse(output) as unknown;

      if (!Array.isArray(parsed)) {
        throw new Error(`Expected an array, received ${typeof parsed}.`);
      }

      for (const timeZone of parsed) {
        if (typeof timeZone === "string" && shouldIncludeTimeZone(timeZone)) {
          supported.add(timeZone);
        }
      }
    } catch (error) {
      console.warn(`Unable to query ${runner.label} supported time zones: ${String(error)}`);
    }
  }

  return supported;
}

function createEntriesWithTransitionLookup(
  timeZones: readonly string[],
  sampleDates: readonly Date[],
  resolveVariant: (date: Date, timeZone: string) => { abbreviation: string; offset: string },
): { entries: TimeZoneAbbreviations; transitionLookup: string[] } {
  const offsetsByTimeZone = new Map<string, TimeZoneOffsetEntry>();
  const transitionSignatureByTimeZone = new Map<string, string>();
  const signatures = new Set<string>([""]);

  for (const timeZone of timeZones) {
    offsetsByTimeZone.set(timeZone, createEntry(timeZone, [...sampleDates], resolveVariant));
    const signature = getTransitionSignature(timeZone, year);

    transitionSignatureByTimeZone.set(timeZone, signature);
    signatures.add(signature);
  }

  const transitionLookup = [
    "",
    ...[...signatures]
      .filter((signature) => signature.length > 0)
      .sort((signatureA, signatureB) => signatureA.localeCompare(signatureB)),
  ];
  const transitionIndexBySignature = new Map(
    transitionLookup.map((signature, index) => [signature, index] as const),
  );
  const entries: TimeZoneAbbreviations = {};

  for (const timeZone of timeZones) {
    const offsets = offsetsByTimeZone.get(timeZone);
    const signature = transitionSignatureByTimeZone.get(timeZone) ?? "";
    const transitionIndex = transitionIndexBySignature.get(signature);

    if (!offsets) {
      throw new Error(`Missing abbreviation entry for "${timeZone}".`);
    }

    if (transitionIndex === undefined) {
      throw new Error(`Missing transition lookup index for signature "${signature}".`);
    }

    entries[timeZone] = Object.fromEntries(
      Object.entries(offsets).map(([offset, abbreviation]) => [offset, `${abbreviation}/${transitionIndex}`]),
    );
  }

  return { entries, transitionLookup };
}

function getTransitionSignature(timeZone: string, targetYear: number): string {
  const yearStart = Date.UTC(targetYear, 0, 1);
  const nextYearStart = Date.UTC(targetYear + 1, 0, 1);
  const monthDays = new Set<string>();
  let dayStart = yearStart;
  let startOffset = getOffset(yearStart, timeZone);

  for (let dayEnd = yearStart + MS_PER_DAY; dayEnd <= nextYearStart; dayEnd += MS_PER_DAY) {
    const endOffset = getOffset(dayEnd, timeZone);

    if (startOffset !== endOffset) {
      const transitions = findTransitionsInWindow(timeZone, dayStart, dayEnd, startOffset);

      for (const transition of transitions) {
        monthDays.add(getMonthDay(transition, timeZone));
      }
    }

    dayStart = dayEnd;
    startOffset = endOffset;
  }

  return [...monthDays].sort((monthDayA, monthDayB) => monthDayA.localeCompare(monthDayB)).join(",");
}

function findTransitionsInWindow(
  timeZone: string,
  start: number,
  end: number,
  startOffset: string,
): number[] {
  const transitions: number[] = [];
  let cursor = start;
  let cursorOffset = startOffset;

  while (cursor < end) {
    const probe = Math.min(cursor + MS_PER_HOUR, end);
    const probeOffset = getOffset(probe, timeZone);

    if (probeOffset === cursorOffset) {
      cursor = probe;
      continue;
    }

    const transition = findTransitionMinute(timeZone, cursor, probe, cursorOffset);

    transitions.push(transition);
    cursor = Math.min(transition + MS_PER_MINUTE, end);
    cursorOffset = getOffset(cursor, timeZone);
  }

  return transitions;
}

function findTransitionMinute(
  timeZone: string,
  lo: number,
  hi: number,
  oldOffset: string,
): number {
  let left = lo;
  let right = hi;

  while (right - left > MS_PER_MINUTE) {
    const midpoint = alignToMinute(left + Math.floor((right - left) / 2));
    const mid = midpoint <= left ? left + MS_PER_MINUTE : midpoint;
    const midOffset = getOffset(mid, timeZone);

    if (midOffset === oldOffset) {
      left = mid;
    } else {
      right = mid;
    }
  }

  return alignToMinute(right);
}

function getOffset(timestamp: number, timeZone: string): string {
  const formatter = getOffsetFormatter(timeZone);
  const formatted = formatter.format(new Date(timestamp));

  return parseShortOffset(formatted);
}

function getOffsetFormatter(timeZone: string): Intl.DateTimeFormat {
  const cached = offsetFormatterCache.get(timeZone);

  if (cached) {
    return cached;
  }

  const formatter = new Intl.DateTimeFormat("en-US", {
    timeZone,
    timeZoneName: "shortOffset",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hourCycle: "h23",
  });

  offsetFormatterCache.set(timeZone, formatter);

  return formatter;
}

function parseShortOffset(formatted: string): string {
  const match = /\b(?:GMT|UTC)(?<sign>[+-])(?<hours>\d{1,2})(?::(?<minutes>\d{2}))?\b/.exec(formatted);

  if (!match?.groups) {
    if (/\b(?:GMT|UTC)\b/.test(formatted)) {
      return "+00:00";
    }

    throw new Error(`Unable to parse UTC offset from "${formatted}".`);
  }

  if (match.groups.hours === "0" && !match.groups.minutes) {
    return "+00:00";
  }

  const sign = match.groups.sign;
  const hours = Number(match.groups.hours);
  const minutes = Number(match.groups.minutes ?? "0");

  return `${sign}${pad2(hours)}:${pad2(minutes)}`;
}

function getMonthDay(timestamp: number, timeZone: string): string {
  const formatter = getMonthDayFormatter(timeZone);
  const parts = formatter.formatToParts(new Date(timestamp));
  const month = parts.find((part) => part.type === "month")?.value;
  const day = parts.find((part) => part.type === "day")?.value;

  if (!month || !day) {
    throw new Error(`Unable to read month/day for "${timeZone}" at ${new Date(timestamp).toISOString()}.`);
  }

  return `${month}-${day}`;
}

function getMonthDayFormatter(timeZone: string): Intl.DateTimeFormat {
  const cached = monthDayFormatterCache.get(timeZone);

  if (cached) {
    return cached;
  }

  const formatter = new Intl.DateTimeFormat("en-US", {
    timeZone,
    month: "2-digit",
    day: "2-digit",
    hourCycle: "h23",
  });

  monthDayFormatterCache.set(timeZone, formatter);

  return formatter;
}

function alignToMinute(timestamp: number): number {
  return Math.floor(timestamp / MS_PER_MINUTE) * MS_PER_MINUTE;
}

function pad2(value: number): string {
  return String(value).padStart(2, "0");
}
