import { readFile, writeFile } from "node:fs/promises";

import {
  addAliasEntries,
  createIanaTzdbResolver,
  createEntry,
  getSampleDates,
  shouldIncludeTimeZone,
  serializeEntries,
  serializeEntry,
  IANA_TZDB_SOURCE_FILES,
  type TimeZoneAbbreviations,
} from "./utils.ts";

const year = new Date().getUTCFullYear();
const sampleDates = getSampleDates(year);
const ianaTzdb = createIanaTzdbResolver();

const timeZones = Intl.supportedValuesOf("timeZone").filter(shouldIncludeTimeZone);
const aliasGroups = await createAliasGroups(timeZones);

if (!timeZones.includes("UTC")) {
  timeZones.unshift("UTC");
}

try {
  const entries = Object.fromEntries(
    timeZones.map((timeZone) => [timeZone, createEntry(timeZone, sampleDates, ianaTzdb.resolveVariant)]),
  );
  addAliasEntries(entries, aliasGroups);

  await writeAliasFile("./timezone-aliases.ts", aliasGroups, ianaTzdb.version);
  await writeAbbreviationFile("../src/timezone-abbreviations.ts", entries, ianaTzdb.version);
} finally {
  ianaTzdb.dispose();
}

async function writeAbbreviationFile(
  path: string,
  abbreviations: TimeZoneAbbreviations,
  tzdbVersion: string,
): Promise<void> {
  const output = `// Generated by scripts/generate-abbreviations.ts.
// Source: IANA tzdb ${tzdbVersion}, sampled at year ${year}.
// This is a current-ish lookup. Regenerate after updating pinned IANA tzdb.

export type TimeZoneAbbreviationEntry = Record<string, string>;

export const TIME_ZONE_ABBREVIATIONS = {
${serializeEntries(abbreviations, serializeEntry)}
} as const satisfies Record<
  string,
  TimeZoneAbbreviationEntry
>;
`;

  await writeFile(new URL(path, import.meta.url), output);
}

async function writeAliasFile(
  path: string,
  aliasGroups: readonly (readonly string[])[],
  tzdbVersion: string,
): Promise<void> {
  const output = `// Generated by scripts/generate-abbreviations.ts.
// Source: IANA tzdb ${tzdbVersion}.
// Maps canonical tzdb names missing from Intl.supportedValuesOf() to supported aliases.
export const TIME_ZONE_ALIAS_GROUPS = [
${aliasGroups.map((aliases) => `  [${aliases.map((alias) => JSON.stringify(alias)).join(", ")}],`).join("\n")}
] as const;
`;

  await writeFile(new URL(path, import.meta.url), output);
}

async function createAliasGroups(
  supportedTimeZones: readonly string[],
): Promise<readonly (readonly string[])[]> {
  const supportedSet = new Set(supportedTimeZones);
  const canonicalSet = await getCanonicalTimeZones();
  const components = await getLinkedTimeZoneComponents();
  const groups: string[][] = [];

  for (const names of components.values()) {
    const supportedNames = [...names]
      .filter((name) => supportedSet.has(name))
      .toSorted((nameA, nameB) => nameA.localeCompare(nameB));
    const missingCanonicalNames = [...names]
      .filter((name) => canonicalSet.has(name) && !supportedSet.has(name) && isAcceptedTimeZone(name))
      .toSorted((nameA, nameB) => nameA.localeCompare(nameB));

    if (supportedNames.length === 0 || missingCanonicalNames.length === 0) {
      continue;
    }

    const aliases = [...new Set([...supportedNames, ...missingCanonicalNames])];

    if (aliases.length > 1) {
      groups.push(aliases);
    }
  }

  return groups.toSorted((groupA, groupB) => groupA[0].localeCompare(groupB[0]));
}

async function getLinkedTimeZoneComponents(): Promise<Map<string, Set<string>>> {
  const allNames = new Set<string>();
  const edges: [string, string][] = [];

  for (const sourceFile of IANA_TZDB_SOURCE_FILES) {
    const source = await readPinnedTzdbFile(sourceFile);

    for (const line of source.split(/\r?\n/)) {
      const trimmed = line.trim();

      if (!trimmed || trimmed.startsWith("#")) {
        continue;
      }

      const [keyword, target, linkName] = trimmed.split(/\s+/);

      if (keyword !== "Link" || !target || !linkName) {
        continue;
      }

      if (!shouldIncludeTimeZone(target) || !shouldIncludeTimeZone(linkName)) {
        continue;
      }

      allNames.add(target);
      allNames.add(linkName);
      edges.push([target, linkName]);
    }
  }

  const parents = new Map<string, string>();

  for (const name of allNames) {
    parents.set(name, name);
  }

  const find = (name: string): string => {
    const parent = parents.get(name);

    if (!parent) {
      parents.set(name, name);
      return name;
    }

    if (parent === name) {
      return name;
    }

    const root = find(parent);
    parents.set(name, root);
    return root;
  };

  const union = (nameA: string, nameB: string): void => {
    const rootA = find(nameA);
    const rootB = find(nameB);

    if (rootA !== rootB) {
      parents.set(rootB, rootA);
    }
  };

  for (const [target, linkName] of edges) {
    union(target, linkName);
  }

  const components = new Map<string, Set<string>>();

  for (const name of allNames) {
    const root = find(name);
    const component = components.get(root);

    if (component) {
      component.add(name);
    } else {
      components.set(root, new Set([name]));
    }
  }

  return components;
}

async function getCanonicalTimeZones(): Promise<Set<string>> {
  const names = new Set<string>();
  const files = ["zone.tab", "zone1970.tab"];

  for (const fileName of files) {
    const source = await readPinnedTzdbFile(fileName);

    for (const line of source.split(/\r?\n/)) {
      if (!line || line.startsWith("#")) {
        continue;
      }

      const columns = line.split("\t");
      const name = columns[2];

      if (name && shouldIncludeTimeZone(name)) {
        names.add(name);
      }
    }
  }

  return names;
}

async function readPinnedTzdbFile(fileName: string): Promise<string> {
  try {
    return await readFile(new URL(`./tzdb/data/${fileName}`, import.meta.url), "utf8");
  } catch (error) {
    throw new Error(
      `Pinned IANA tzdb file "${fileName}" is missing. Run \`npm run generate\` (or \`npm run update-tzdb\`) and retry.`,
      { cause: error },
    );
  }
}

function isAcceptedTimeZone(timeZone: string): boolean {
  try {
    new Intl.DateTimeFormat("en-US", { timeZone });
    return true;
  } catch {
    return false;
  }
}
