// Generated by scripts/generate-abbreviations.ts.
// Source: IANA tzdb 2026b.
// Maps canonical tzdb names missing from Intl.supportedValuesOf() to supported aliases.
export const TIME_ZONE_ALIAS_GROUPS = [
  ["Africa/Addis_Ababa", "Africa/Asmera", "Africa/Dar_es_Salaam", "Africa/Djibouti", "Africa/Kampala", "Africa/Mogadishu", "Africa/Nairobi", "Indian/Antananarivo", "Indian/Comoro", "Indian/Mayotte", "Africa/Asmara"],
  ["America/Buenos_Aires", "America/Argentina/Buenos_Aires"],
  ["America/Catamarca", "America/Argentina/Catamarca"],
  ["America/Cayman", "America/Coral_Harbour", "America/Panama", "America/Atikokan"],
  ["America/Cordoba", "America/Argentina/Cordoba"],
  ["America/Godthab", "America/Nuuk"],
  ["America/Indianapolis", "America/Indiana/Indianapolis"],
  ["America/Jujuy", "America/Argentina/Jujuy"],
  ["America/Louisville", "America/Kentucky/Louisville"],
  ["America/Mendoza", "America/Argentina/Mendoza"],
  ["Antarctica/DumontDUrville", "Pacific/Port_Moresby", "Pacific/Truk", "Pacific/Chuuk"],
  ["Asia/Calcutta", "Asia/Kolkata"],
  ["Asia/Katmandu", "Asia/Kathmandu"],
  ["Asia/Rangoon", "Indian/Cocos", "Asia/Yangon"],
  ["Asia/Saigon", "Asia/Ho_Chi_Minh"],
  ["Atlantic/Faeroe", "Atlantic/Faroe"],
  ["Europe/Kiev", "Europe/Kyiv"],
  ["Pacific/Enderbury", "Pacific/Kanton"],
  ["Pacific/Guadalcanal", "Pacific/Ponape", "Pacific/Pohnpei"],
] as const;
