// Generated by scripts/generate-abbreviations.ts.
// Source: IANA tzdb 2026b, transition signatures sampled at year 2026.
export const TIME_ZONE_TRANSITION_LOOKUP = [
  "",
  "02-15,03-22",
  "03-08,11-01",
  "03-27,10-25",
  "03-28,10-24",
  "03-29,10-24",
  "03-29,10-25",
  "04-04,09-05",
  "04-04,09-06",
  "04-05,09-27",
  "04-05,10-04",
  "04-24,10-29",
] as const;
