// Generated by scripts/generate-abbreviations.ts.
// Source: IANA tzdb 2026b.
// Groups are [canonical, ...aliases], where canonical names come from tzdb
// canonical sources and aliases are non-canonical names present in
// Intl.supportedValuesOf("timeZone") from either Node or Bun runtimes.
export const TIME_ZONE_ALIAS_GROUPS = [
  ["Africa/Addis_Ababa", "Africa/Asmera"],
  ["America/Argentina/Buenos_Aires", "America/Buenos_Aires"],
  ["America/Argentina/Catamarca", "America/Catamarca"],
  ["America/Argentina/Cordoba", "America/Cordoba"],
  ["America/Argentina/Jujuy", "America/Jujuy"],
  ["America/Argentina/Mendoza", "America/Mendoza"],
  ["America/Atikokan", "America/Coral_Harbour"],
  ["America/Indiana/Indianapolis", "America/Indianapolis"],
  ["America/Kentucky/Louisville", "America/Louisville"],
  ["America/Nuuk", "America/Godthab"],
  ["Asia/Ho_Chi_Minh", "Asia/Saigon"],
  ["Asia/Kathmandu", "Asia/Katmandu"],
  ["Asia/Kolkata", "Asia/Calcutta"],
  ["Asia/Ulaanbaatar", "Asia/Choibalsan"],
  ["Asia/Yangon", "Asia/Rangoon"],
  ["Atlantic/Faroe", "Atlantic/Faeroe"],
  ["Europe/Kyiv", "Europe/Kiev"],
  ["Pacific/Guadalcanal", "Pacific/Ponape"],
  ["Pacific/Kanton", "Pacific/Enderbury"],
] as const;
